=head1 My Amazing Library

=begin HTML

<p><a href="https://gitter.im/myorg/myrepo?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"><img src="https://badges.gitter.im/Join%20Chat.svg" alt="Join the chat at https://gitter.im/myorg/myrepo"></a></p>

=end HTML

=head2 Features

It does amazing things!
